language: ruby
rvm:
  - 2.1.2

before_install:
  - echo host localhost >> ~/.ssh/config
  - echo   user git >> ~/.ssh/config
  - echo   identityfile ~/git >> ~/.ssh/config
  - echo   port 22 >> ~/.ssh/config
  - echo NoHostAuthenticationForLocalhost yes >> ~/.ssh/config
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - git config --global user.email "travis@travis.com"
  - git config --global user.name "Travis CI"

install:
  - travis_wait bundle install --path=~/.bundle --without development production console
  - wget http://mirror.its.dal.ca/apache/subversion/subversion-1.8.14.tar.gz
  - tar xzf subversion-1.8.14.tar.gz
  - wget http://www.sqlite.org/sqlite-amalgamation-3071501.zip
  - unzip sqlite-amalgamation-3071501.zip
  - mv sqlite-amalgamation-3071501 subversion-1.8.14/sqlite-amalgamation
  - cd subversion-1.8.14
  - LDFLAGS="-L/home/travis/.rvm/rubies/ruby-2.1.2/lib/" ./configure --prefix=/home/travis/.rvm/rubies/ruby-2.1.2/
  - make
  - make swig-rb
  - make install
  - make install-swig-rb
  - cd ..

before_script:
  - cp config/database.yml.ci config/database.yml
  - psql -c 'create database markus_test;' -U postgres
  - bundle exec rake db:test:prepare

script:
  - bundle exec rake test
  - bundle exec rspec

notifications:
  email: false

bundler_args: --retry 10

addons:
  apt:
    packages:
    - sshpass
    - cmake
    - libssh2*
    - libgit2*
    - ruby1.9.1-dev
    - libaprutil1-dev
    - swig

cache:
  bundler
  
sudo: false
